[package]
name = "wee-common"
version = "0.1.0"
authors = ["Ross <yeahross@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.111", features = ["derive"] }
log = "0.4.8"